[package]
name = "infosechonors"
version = "0.1.0"
authors = ["Kevin B. Owens <owens.bradyn1999@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
